### ISSUE TITLE
The site is returning 404 errors

### ISSUE THREAD

**Issue by ajtribick** [harfbuzz/harfbuzz.github.io#4]
Looks like the site has stopped working. As a guess, is it still set to serve the files from the master branch?

**Comment by behdad** [comment]
Humm. Thanks. I'll make a push to see if it helps.

**Comment by ajtribick** [comment]
Could be the repository settings? Perhaps switching the branch back and forth will trigger it? https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

**Comment by khaledhosny** [comment]
This is fixed now.
